//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Direct_Response.UsersDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int User_Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Full_name { get; set; }
        public string Email { get; set; }
        public string Image { get; set; }
    }
}
