//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Direct_Response_Web_Service.MessagesDb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Direct_Response_UsersDbEntities : DbContext
    {
        public Direct_Response_UsersDbEntities()
            : base("name=Direct_Response_UsersDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<NonDeliveredMessage> NonDeliveredMessages { get; set; }
    
        public virtual int NonDeliveredDelete(Nullable<int> idMessage)
        {
            var idMessageParameter = idMessage.HasValue ?
                new ObjectParameter("idMessage", idMessage) :
                new ObjectParameter("idMessage", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NonDeliveredDelete", idMessageParameter);
        }
    
        public virtual int NonDeliveredInsert(string to, Nullable<int> toId, string from, Nullable<int> fromId, string fromImage, string message)
        {
            var toParameter = to != null ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(string));
    
            var toIdParameter = toId.HasValue ?
                new ObjectParameter("toId", toId) :
                new ObjectParameter("toId", typeof(int));
    
            var fromParameter = from != null ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(string));
    
            var fromIdParameter = fromId.HasValue ?
                new ObjectParameter("fromId", fromId) :
                new ObjectParameter("fromId", typeof(int));
    
            var fromImageParameter = fromImage != null ?
                new ObjectParameter("fromImage", fromImage) :
                new ObjectParameter("fromImage", typeof(string));
    
            var messageParameter = message != null ?
                new ObjectParameter("message", message) :
                new ObjectParameter("message", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NonDeliveredInsert", toParameter, toIdParameter, fromParameter, fromIdParameter, fromImageParameter, messageParameter);
        }
    }
}
