//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Direct_Response_Web_Service.MessagesDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonDeliveredMessage
    {
        public int IdMessage { get; set; }
        public string Message { get; set; }
        public int FromId { get; set; }
        public string From { get; set; }
        public string FromImage { get; set; }
        public int ToId { get; set; }
        public string To { get; set; }
    }
}
